### ISSUE TITLE
kpsewhich: not found

### ISSUE THREAD

**Issue by koenwybo** [TeX-Live/tlcockpit#10]
Installed from texlive-install script. 
tlcockpit is included but does not start: ./tlcockpit: 1: ./tlcockpit: kpsewhich: not found
Error: Unable to access jarfile

OS is Debian 9: java openjdk and openjfx installed

openjfx/stable,now 8u141-b14-3~deb9u1 amd64 [geïnstalleerd]
libopenjfx-java/stable,stable,now 8u141-b14-3~deb9u1 all [geïnstalleerd,automatisch]
openjdk-8-jre-headless/stable,stable,now 8u151-b12-1~deb9u1 amd64 [geïnstalleerd,automatisch]
  OpenJDK Java runtime, using Hotspot JIT (headless)
openjdk-8-jre/stable,stable,now 8u151-b12-1~deb9u1 amd64 [geïnstalleerd,automatisch]
  OpenJDK Java runtime, using Hotspot JIT

Invoking script: 

root@genesis:/usr/local/texlive# java -jar ./2017/texmf-dist/scripts/tlcockpit/tlcockpit.jar
Gtk-Message: Failed to load module "canberra-gtk-module"
Exception in Application start method
Exception in Application stop method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Cannot run program "kpsewhich": error=2, Bestand of map bestaat niet
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:71)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:115)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:131)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:104)
	at TeXLive.TlmgrProcess.<init>(TlmgrProcess.scala:23)
	at TLCockpit.ApplicationMain$.initialize_tlmgr(ApplicationMain.scala:1382)
	at TLCockpit.ApplicationMain$.delayedEndpoint$TLCockpit$ApplicationMain$1(ApplicationMain.scala:1583)
	at TLCockpit.ApplicationMain$delayedInit$body.apply(ApplicationMain.scala:58)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scalafx.application.JFXApp.$anonfun$init$1(JFXApp.scala:297)
	at scalafx.application.JFXApp.$anonfun$init$1$adapted(JFXApp.scala:297)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.generic.TraversableForwarder.foreach(TraversableForwarder.scala:35)
	at scala.collection.generic.TraversableForwarder.foreach$(TraversableForwarder.scala:35)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:44)
	at scalafx.application.JFXApp.init(JFXApp.scala:297)
	at scalafx.application.JFXApp.init$(JFXApp.scala:297)
	at TLCockpit.ApplicationMain$.init(ApplicationMain.scala:58)
	at scalafx.application.AppHelper.start(AppHelper.scala:33)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
	... 1 more
Caused by: java.io.IOException: error=2, Bestand of map bestaat niet
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 30 more

root@genesis:/usr/local/texlive# java -jar -dd ./2017/texmf-dist/scripts/tlcockpit/tlcockpit.jar
Unrecognized option: -dd
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by norbusan** [comment]
you have to have kpsewhich in the path, that is you have to have /use/local/texlive/2017/bin/ARCH in the PATH.
concerning the -dd option, you have to give it after the .jar file, but it will not change anything here.

**Comment by koenwybo** [comment]
Thanks, everything is working fine now.

**Comment by norbusan** [comment]
Ok, thanks for the feedback, closing this issue.
