### ISSUE TITLE
Updates pane does not show available updates

### ISSUE THREAD

**Issue by mlep** [TeX-Live/tlcockpit#20]
After starting TLCockpit, and clicking on the Updates pane, the pane shows "Loading updates" forever. 

An exception is thrown when clicking on the Updates pane. This occurs with OpenJDK versions 11 and 17. See below.

```
$ sudo tlcockpit 
11:39:57 [JavaFX Application Thread] WARN  TLCockpit.ApplicationMain$ - Build and run versions disagree: build: 14, run: 11, trying anyway!
11:39:57 [JavaFX Application Thread] INFO  TLCockpit.ApplicationMain$ - Running on Java Version 11
Exception in thread "JavaFX Application Thread" java.lang.NumberFormatException: For input string: "-"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Long.parseLong(Long.java:682)
	at java.base/java.lang.Long.parseLong(Long.java:817)
	at scala.collection.immutable.StringLike.toLong(StringLike.scala:309)
	at scala.collection.immutable.StringLike.toLong$(StringLike.scala:309)
	at scala.collection.immutable.StringOps.toLong(StringOps.scala:33)
	at TLCockpit.ApplicationMain$.parse_one_update_line(ApplicationMain.scala:850)
	at TLCockpit.ApplicationMain$.$anonfun$load_updates_update_upds_view$3(ApplicationMain.scala:881)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.map(TraversableLike.scala:273)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:266)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
	at TLCockpit.ApplicationMain$.$anonfun$load_updates_update_upds_view$1(ApplicationMain.scala:880)
	at TLCockpit.ApplicationMain$.$anonfun$load_updates_update_upds_view$1$adapted(ApplicationMain.scala:871)
	at TLCockpit.ApplicationMain$.$anonfun$tlmgr_run_one_cmd$3(ApplicationMain.scala:1642)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scalafx.application.Platform$$anon$1.run(Platform.scala:147)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

```
$ sudo tlcockpit 
11:44:05 [JavaFX Application Thread] WARN  TLCockpit.ApplicationMain$ - Build and run versions disagree: build: 14, run: 17, trying anyway!
11:44:05 [JavaFX Application Thread] INFO  TLCockpit.ApplicationMain$ - Running on Java Version 17
Exception in thread "JavaFX Application Thread" java.lang.NumberFormatException: For input string: "-"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Long.parseLong(Long.java:701)
	at java.base/java.lang.Long.parseLong(Long.java:836)
	at scala.collection.immutable.StringLike.toLong(StringLike.scala:309)
	at scala.collection.immutable.StringLike.toLong$(StringLike.scala:309)
	at scala.collection.immutable.StringOps.toLong(StringOps.scala:33)
	at TLCockpit.ApplicationMain$.parse_one_update_line(ApplicationMain.scala:850)
	at TLCockpit.ApplicationMain$.$anonfun$load_updates_update_upds_view$3(ApplicationMain.scala:881)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.map(TraversableLike.scala:273)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:266)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
	at TLCockpit.ApplicationMain$.$anonfun$load_updates_update_upds_view$1(ApplicationMain.scala:880)
	at TLCockpit.ApplicationMain$.$anonfun$load_updates_update_upds_view$1$adapted(ApplicationMain.scala:871)
	at TLCockpit.ApplicationMain$.$anonfun$tlmgr_run_one_cmd$3(ApplicationMain.scala:1642)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scalafx.application.Platform$$anon$1.run(Platform.scala:147)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by norbusan** [comment]
Hmmm, I cannot reproduce it. I have just tested tlcockpit and updates work fine.

Could you try without sudo somehow?

**Comment by mlep** [comment]
Without sudo, I get the same behavior (and error message). :face_with_spiral_eyes:

**Comment by norbusan** [comment]
@mlep Can you please
- start tlcockpit
- click on the `Updates` tab
- wait for the error to be thrown
- click on the `Debug` line at the bottom of the window
- click on the `Logging` tab there
- copy the complete output given there
- click on the `Error` tab there
- copy the complete output given there
- send me or include here the above outputs

Thanks!

**Comment by mlep** [comment]
For your information, the Java error is thrown as soon as I click on the `Updates` tab.

The `Errors` tab is empty.

Below is the log.
Everything up to `finish load https://ctan.tetaneutral.net/systems/texlive/tlnet` is displayed _before_ clicking on the `Updates` tab.

Thank you for maintaining `tlcockpit` !


```

D:Cannot open package log file for appending: /usr/local/texlive/2023/texmf-var/web2c/tlmgr.log
D:Will not log package installation/removal/update for this run
D:Cannot open command log file for appending: /usr/local/texlive/2023/texmf-var/web2c/tlmgr-commands.log
D:Will not log output of executed commands for this run
D:tlmgr:main: ::tldownload_server hash:: {enabled:1,errorcount:0,initcount:1,ua:LWP::UserAgent=HASH(0x560491a50228)}
D:setup_programs: preferring system versions
D:program df found in path
D:program curl found in path
D:program wget found in path
D:TLUtils::setup_programs: checking for ssl enabled wget
D:TLUtils::setup_programs: wget has ssl, final wget args: --no-check-certificate --user-agent=texlive/wget --tries=4 --timeout=30 -q -O
D:program lz4 found in path
D:program gzip found in path
D:program xz found in path
D:Using checksum method digest::sha
D:Testing for gpg in gpg
D: ... gpg ok! [gpg --version >/dev/null 2>&1]
D:gpg command line: gpg --homedir "/usr/local/texlive/2023/tlpkg/gpg" --no-secmem-warning --no-permission-warning --lock-never 
D:will verify cryptographic signatures
start load https://ctan.tetaneutral.net/systems/texlive/tlnet
D:persistent connection set up, trying to get https://ctan.tetaneutral.net/systems/texlive/tlnet/tlpkg/texlive.tlpdb.sha512 (for /tmp/U3joTaAUs6/sMIyixIdeJ)
D:TLUtils::download_file: downloading using lwp succeeded
D:persistent connection set up, trying to get https://ctan.tetaneutral.net/systems/texlive/tlnet/tlpkg/texlive.tlpdb.sha512.asc (for /tmp/U3joTaAUs6/2AdvFS8RDv)
D:TLUtils::download_file: downloading using lwp succeeded
D:STATUS OUTPUT
[GNUPG:] NEWSIG
[GNUPG:] KEY_CONSIDERED C78B82D8C79512F79CC0D7C80D5E5D9106BAB6BC 0
[GNUPG:] SIG_ID YJykWeJIGmIHocTnGigqhFo0o7U 2023-04-17 1681775701
[GNUPG:] KEY_CONSIDERED C78B82D8C79512F79CC0D7C80D5E5D9106BAB6BC 0
[GNUPG:] GOODSIG 4CE1877E19438C70 TeX Live Distribution <tex-live@tug.org>
[GNUPG:] VALIDSIG D8F2F86057A857E42A88106A4CE1877E19438C70 2023-04-17 1681775701 0 4 0 1 10 01 C78B82D8C79512F79CC0D7C80D5E5D9106BAB6BC
[GNUPG:] KEY_CONSIDERED C78B82D8C79512F79CC0D7C80D5E5D9106BAB6BC 0
[GNUPG:] TRUST_ULTIMATE 0 pgp
[GNUPG:] VERIFICATION_COMPLIANCE_MODE 23D:verification succeeded, output:
gpg: Signature faite le mar. 18 avril 2023 01:55:01 CEST
gpg:                avec la clef RSA 4CE1877E19438C70
gpg: RemarqueÂ : la base de confiance n'est pas accessible en Ã©criture
gpg: Bonne signature de Â«Â TeX Live Distribution <tex-live@tug.org>Â Â» [ultime]

D:cryptographic signature of https://ctan.tetaneutral.net/systems/texlive/tlnet/tlpkg/texlive.tlpdb.sha512 verified
D:verify_checksum: found remote digest
  955912aee6ff70411d0b45a31219aebd9ca0081506fa93f82f37aa40f461303700a55cff12e4d90a99bd12d0d42e296e187c760d8301fa9b97d228e179653fdd
from
  /tmp/U3joTaAUs6/sMIyixIdeJ
for
  /usr/local/texlive/2023/tlpkg/texlive.tlpdb.main.fbec35173e86b9f184aa1ae67b227d82
and
  https://ctan.tetaneutral.net/systems/texlive/tlnet/tlpkg/texlive.tlpdb.sha512
D:tlchecksum(/usr/local/texlive/2023/tlpkg/texlive.tlpdb.main.fbec35173e86b9f184aa1ae67b227d82): ===6fe98557d601884a243809c6ce1d6af63b17686142dfff4a1e9b48b2a3f5334a5bc3c14d2723127407e6db328671a40de6c64db0ea125142863ee21f9ffdb822===
D:verify_checksum: local_digest = 6fe98557d601884a243809c6ce1d6af63b17686142dfff4a1e9b48b2a3f5334a5bc3c14d2723127407e6db328671a40de6c64db0ea125142863ee21f9ffdb822
D:TLPDB.pm: trying to initialize from https://ctan.tetaneutral.net/systems/texlive/tlnet/tlpkg/texlive.tlpdb
D:trying to download https://ctan.tetaneutral.net/systems/texlive/tlnet/tlpkg/texlive.tlpdb.xz to /tmp/U3joTaAUs6/0DVZXom_20
D:persistent connection set up, trying to get https://ctan.tetaneutral.net/systems/texlive/tlnet/tlpkg/texlive.tlpdb.xz (for /tmp/U3joTaAUs6/0DVZXom_20)
D:TLUtils::download_file: downloading using lwp succeeded
D:decompressing /tmp/U3joTaAUs6/0DVZXom_20 to /tmp/U3joTaAUs6/QNe0zA9f7e
D:TLUtils::system_pipe: calling "xz" -dcf < "/tmp/U3joTaAUs6/0DVZXom_20" > "/tmp/U3joTaAUs6/QNe0zA9f7e"
D:TLUtils::system_pipe: removing /tmp/U3joTaAUs6/0DVZXom_20
D:found the uncompressed xz file
D:persistent connection set up, trying to get https://ctan.tetaneutral.net/systems/texlive/tlnet/tlpkg/texlive.tlpdb.sha512 (for /tmp/U3joTaAUs6/2SFNZe2qWc)
D:TLUtils::download_file: downloading using lwp succeeded
D:persistent connection set up, trying to get https://ctan.tetaneutral.net/systems/texlive/tlnet/tlpkg/texlive.tlpdb.sha512.asc (for /tmp/U3joTaAUs6/lx6BXNbxYH)
D:TLUtils::download_file: downloading using lwp succeeded
D:STATUS OUTPUT
[GNUPG:] NEWSIG
[GNUPG:] KEY_CONSIDERED C78B82D8C79512F79CC0D7C80D5E5D9106BAB6BC 0
[GNUPG:] SIG_ID YJykWeJIGmIHocTnGigqhFo0o7U 2023-04-17 1681775701
[GNUPG:] KEY_CONSIDERED C78B82D8C79512F79CC0D7C80D5E5D9106BAB6BC 0
[GNUPG:] GOODSIG 4CE1877E19438C70 TeX Live Distribution <tex-live@tug.org>
[GNUPG:] VALIDSIG D8F2F86057A857E42A88106A4CE1877E19438C70 2023-04-17 1681775701 0 4 0 1 10 01 C78B82D8C79512F79CC0D7C80D5E5D9106BAB6BC
[GNUPG:] KEY_CONSIDERED C78B82D8C79512F79CC0D7C80D5E5D9106BAB6BC 0
[GNUPG:] TRUST_ULTIMATE 0 pgp
[GNUPG:] VERIFICATION_COMPLIANCE_MODE 23D:verification succeeded, output:
gpg: Signature faite le mar. 18 avril 2023 01:55:01 CEST
gpg:                avec la clef RSA 4CE1877E19438C70
gpg: RemarqueÂ : la base de confiance n'est pas accessible en Ã©criture
gpg: Bonne signature de Â«Â TeX Live Distribution <tex-live@tug.org>Â Â» [ultime]

D:cryptographic signature of https://ctan.tetaneutral.net/systems/texlive/tlnet/tlpkg/texlive.tlpdb.sha512 verified
D:verify_checksum: found remote digest
  955912aee6ff70411d0b45a31219aebd9ca0081506fa93f82f37aa40f461303700a55cff12e4d90a99bd12d0d42e296e187c760d8301fa9b97d228e179653fdd
from
  /tmp/U3joTaAUs6/2SFNZe2qWc
for
  /tmp/U3joTaAUs6/QNe0zA9f7e
and
  https://ctan.tetaneutral.net/systems/texlive/tlnet/tlpkg/texlive.tlpdb.sha512
D:tlchecksum(/tmp/U3joTaAUs6/QNe0zA9f7e): ===955912aee6ff70411d0b45a31219aebd9ca0081506fa93f82f37aa40f461303700a55cff12e4d90a99bd12d0d42e296e187c760d8301fa9b97d228e179653fdd===
D:verify_checksum: local_digest = 955912aee6ff70411d0b45a31219aebd9ca0081506fa93f82f37aa40f461303700a55cff12e4d90a99bd12d0d42e296e187c760d8301fa9b97d228e179653fdd
D:checksum of local copy identical with remote hash
D:Cannot save remote TeX Live database to /usr/local/texlive/2023/tlpkg/texlive.tlpdb.main.fbec35173e86b9f184aa1ae67b227d82: Permission denied
finish load https://ctan.tetaneutral.net/systems/texlive/tlnet
D:Testing for gpg in gpg
D: ... gpg ok! [gpg --version >/dev/null 2>&1]
D:gpg command line: gpg --homedir "/usr/local/texlive/2023/tlpkg/gpg" --no-secmem-warning --no-permission-warning --lock-never 
D:will verify cryptographic signatures
D:Automatic backups activated, keeping 1 backups.
D:tlmgr: new pkgs: 
D:tlmgr: deleted : 
D:tlmgr: forced  : 
D:texlive-scripts upd package
```

**Comment by norbusan** [comment]
Thanks, there we go
> ```
> D:Cannot save remote TeX Live database to > /usr/local/texlive/2023/tlpkg/texlive.tlpdb.main.fbec35173e86b9f184aa1ae67b227d82: Permission denied
> ```

It seems that there are permission problems. The same problem appears already before that right at the top:
```
D:Cannot open package log file for appending: /usr/local/texlive/2023/texmf-var/web2c/tlmgr.log
D:Will not log package installation/removal/update for this run
D:Cannot open command log file for appending: /usr/local/texlive/2023/texmf-var/web2c/tlmgr-commands.log
D:Will not log output of executed commands for this run
```

Can you redo this as root, or check the permissions there?

**Comment by mlep** [comment]
Sure!

Below the log with tlcockpit launched as root.
The `Errors` tab remains empty. 

````
D:appending to package log file: /usr/local/texlive/2023/texmf-var/web2c/tlmgr.log
D:appending to command log file: /usr/local/texlive/2023/texmf-var/web2c/tlmgr-commands.log
D:setup_programs: preferring system versions
D:program df found in path
D:program curl found in path
D:program wget found in path
D:TLUtils::setup_programs: checking for ssl enabled wget
D:TLUtils::setup_programs: wget has ssl, final wget args: --no-check-certificate --user-agent=texlive/wget --tries=4 --timeout=30 -q -O
D:program lz4 found in path
D:program gzip found in path
D:program xz found in path
D:Using checksum method digest::sha
D:Testing for gpg in gpg
D: ... gpg ok! [gpg --version >/dev/null 2>&1]
D:gpg command line: gpg --homedir "/usr/local/texlive/2023/tlpkg/gpg" --no-secmem-warning --no-permission-warning --lock-never 
D:will verify cryptographic signatures
start load https://ctan.tetaneutral.net/systems/texlive/tlnet
D:persistent connection set up, trying to get https://ctan.tetaneutral.net/systems/texlive/tlnet/tlpkg/texlive.tlpdb.sha512 (for /tmp/0YUD7zxBmx/OOTzLLLZCG)
D:TLUtils::download_file: downloading using lwp succeeded
D:persistent connection set up, trying to get https://ctan.tetaneutral.net/systems/texlive/tlnet/tlpkg/texlive.tlpdb.sha512.asc (for /tmp/0YUD7zxBmx/Q_w40nIM6g)
D:TLUtils::download_file: downloading using lwp succeeded
D:STATUS OUTPUT
[GNUPG:] NEWSIG
[GNUPG:] KEY_CONSIDERED C78B82D8C79512F79CC0D7C80D5E5D9106BAB6BC 0
[GNUPG:] SIG_ID YJykWeJIGmIHocTnGigqhFo0o7U 2023-04-17 1681775701
[GNUPG:] KEY_CONSIDERED C78B82D8C79512F79CC0D7C80D5E5D9106BAB6BC 0
[GNUPG:] GOODSIG 4CE1877E19438C70 TeX Live Distribution <tex-live@tug.org>
[GNUPG:] VALIDSIG D8F2F86057A857E42A88106A4CE1877E19438C70 2023-04-17 1681775701 0 4 0 1 10 01 C78B82D8C79512F79CC0D7C80D5E5D9106BAB6BC
[GNUPG:] KEY_CONSIDERED C78B82D8C79512F79CC0D7C80D5E5D9106BAB6BC 0
[GNUPG:] TRUST_ULTIMATE 0 pgp
[GNUPG:] VERIFICATION_COMPLIANCE_MODE 23D:verification succeeded, output:
gpg: Signature faite le mar. 18 avril 2023 01:55:01 CEST
gpg:                avec la clef RSA 4CE1877E19438C70
gpg: Bonne signature de Â«Â TeX Live Distribution <tex-live@tug.org>Â Â» [ultime]

D:cryptographic signature of https://ctan.tetaneutral.net/systems/texlive/tlnet/tlpkg/texlive.tlpdb.sha512 verified
D:verify_checksum: found remote digest
  955912aee6ff70411d0b45a31219aebd9ca0081506fa93f82f37aa40f461303700a55cff12e4d90a99bd12d0d42e296e187c760d8301fa9b97d228e179653fdd
from
  /tmp/0YUD7zxBmx/OOTzLLLZCG
for
  /usr/local/texlive/2023/tlpkg/texlive.tlpdb.main.fbec35173e86b9f184aa1ae67b227d82
and
  https://ctan.tetaneutral.net/systems/texlive/tlnet/tlpkg/texlive.tlpdb.sha512
D:tlchecksum(/usr/local/texlive/2023/tlpkg/texlive.tlpdb.main.fbec35173e86b9f184aa1ae67b227d82): ===955912aee6ff70411d0b45a31219aebd9ca0081506fa93f82f37aa40f461303700a55cff12e4d90a99bd12d0d42e296e187c760d8301fa9b97d228e179653fdd===
D:verify_checksum: local_digest = 955912aee6ff70411d0b45a31219aebd9ca0081506fa93f82f37aa40f461303700a55cff12e4d90a99bd12d0d42e296e187c760d8301fa9b97d228e179653fdd
D:checksum of local copy identical with remote hash
finish load https://ctan.tetaneutral.net/systems/texlive/tlnet
D:Testing for gpg in gpg
D: ... gpg ok! [gpg --version >/dev/null 2>&1]
D:gpg command line: gpg --homedir "/usr/local/texlive/2023/tlpkg/gpg" --no-secmem-warning --no-permission-warning --lock-never 
D:will verify cryptographic signatures
D:Automatic backups activated, keeping 1 backups.
D:tlmgr: new pkgs: 
D:tlmgr: deleted : 
D:tlmgr: forced  : 
D:texlive-scripts upd package
````

**Comment by norbusan** [comment]
Thanks a lot. Very interesting ... that all seems very fine indeed.
I have now installed Java 17, and also made my installation so that only `texlive-scripts` needs an update (similar to you, see:
```
D:texlive-scripts upd package
```
) but I still cannot reproduce this error. 

Can you please try (again as root) the following:
```
java -verbose:class -verbose:module -jar $(kpsewhich --progname=tlcockpit --format=texmfscripts tlcockpit.jar)
```
This will create a lot of output on the console. Wait until the output stopped. Then click on the "Updates" tab and send the output the was generated after that.

Very hard to debug when not reproducible ...

Thanks

**Comment by mlep** [comment]
Well, it disfunctions like a sharm on my computer. ;-)

Here is the output after the click:

````
[13,687s][info][class,load] javafx.scene.Scene$DnDGesture source: file:/usr/local/texlive/2023/texmf-dist/scripts/tlcockpit/tlcockpit.jar
[13,687s][info][class,load] javafx.scene.input.Clipboard source: file:/usr/local/texlive/2023/texmf-dist/scripts/tlcockpit/tlcockpit.jar
[13,687s][info][class,load] javafx.scene.input.Dragboard source: file:/usr/local/texlive/2023/texmf-dist/scripts/tlcockpit/tlcockpit.jar
[13,687s][info][class,load] com.sun.javafx.tk.TKDragSourceListener source: file:/usr/local/texlive/2023/texmf-dist/scripts/tlcockpit/tlcockpit.jar
[13,688s][info][class,load] javafx.scene.Scene$DragDetectedState source: file:/usr/local/texlive/2023/texmf-dist/scripts/tlcockpit/tlcockpit.jar
[13,689s][info][class,load] javafx.scene.Scene$ClickCounter$$Lambda$952/0x00000008010bd0f0 source: javafx.scene.Scene
[13,691s][info][class,load] TLCockpit.ApplicationMain$$$Lambda$953/0x00000008010bd318 source: TLCockpit.ApplicationMain$
[13,693s][info][class,load] com.sun.javafx.scene.control.behavior.ButtonBehavior$$Lambda$954/0x00000008010bdad0 source: com.sun.javafx.scene.control.behavior.ButtonBehavior
[13,746s][info][class,load] TLCockpit.ApplicationMain$$$Lambda$955/0x00000008010bdcf8 source: TLCockpit.ApplicationMain$
[13,746s][info][class,load] TLCockpit.ApplicationMain$$$Lambda$956/0x00000008010be0d0 source: TLCockpit.ApplicationMain$
Exception in thread "JavaFX Application Thread" [13,747s][info][class,load] java.lang.Throwable$PrintStreamOrWriter source: jrt:/java.base
[13,747s][info][class,load] java.lang.Throwable$WrappedPrintStream source: jrt:/java.base
java.lang.NumberFormatException: For input string: "-"
[13,747s][info][class,load] java.lang.StackTraceElement$HashedModules source: jrt:/java.base
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Long.parseLong(Long.java:701)
	at java.base/java.lang.Long.parseLong(Long.java:836)
	at scala.collection.immutable.StringLike.toLong(StringLike.scala:309)
	at scala.collection.immutable.StringLike.toLong$(StringLike.scala:309)
	at scala.collection.immutable.StringOps.toLong(StringOps.scala:33)
	at TLCockpit.ApplicationMain$.parse_one_update_line(ApplicationMain.scala:850)
	at TLCockpit.ApplicationMain$.$anonfun$load_updates_update_upds_view$3(ApplicationMain.scala:881)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.map(TraversableLike.scala:273)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:266)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
	at TLCockpit.ApplicationMain$.$anonfun$load_updates_update_upds_view$1(ApplicationMain.scala:880)
	at TLCockpit.ApplicationMain$.$anonfun$load_updates_update_upds_view$1$adapted(ApplicationMain.scala:871)
	at TLCockpit.ApplicationMain$.$anonfun$tlmgr_run_one_cmd$3(ApplicationMain.scala:1642)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scalafx.application.Platform$$anon$1.run(Platform.scala:147)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:833)
[13,760s][info][class,load] com.sun.javafx.geometry.BoundsUtils source: file:/usr/local/texlive/2023/texmf-dist/scripts/tlcockpit/tlcockpit.jar


````

**Comment by jotagah** [comment]
Greetings,

I have the same issue. Tlcockpit shows the "loading updates" and seems to freeze but is responsible. I am running it inside a wsl ubuntu. I have the "same" configuration in home without that issue. I am using TLShell to update.

Is there any action I have to follow, like reset any tlcockpit configuration? TexLive was installed as user, not as root.

**Comment by jotagah** [comment]
Greetings,

I followed a closed issue tip about running "tlmgr update --all --reinstall-forcibly-removed" and now all is working again. 

Sorry the noise.

**Comment by mlep** [comment]
Tried tlcockpit today. Works well: update carried out.
No idea why it dit not work. No idea why it works now.
Closing...

$tlcockpit 
16:32:18 [JavaFX Application Thread] WARN  TLCockpit.ApplicationMain$ - Build and run versions disagree: build: 14, run: 17, trying anyway!
16:32:18 [JavaFX Application Thread] INFO  TLCockpit.ApplicationMain$ - Running on Java Version 17
16:33:35 [Thread-6] WARN  TeXLive.TlmgrProcess - Exception in outputFn thread: java.io.IOException: Stream closed

16:33:35 [Thread-7] WARN  TeXLive.TlmgrProcess - Exception in outputFn thread: java.io.IOException: Stream closed
