### ISSUE TITLE
undefined symbol: jpeg_resync_to_restart

### ISSUE THREAD

**Issue by ax006ho** [TeX-Live/tlcockpit#9]
On Fedora 27 with a quite recent JDK (openjdk version "1.8.0_161") I get the following error:

$ tlcockpit
Exception in Application start method
Exception in Application stop method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsatisfiedLinkError: /usr/lib/jvm/openjfx/rt/lib/amd64/libjavafx_iio.so: /usr/lib/jvm/openjfx/rt/lib/amd64/libjavafx_iio.so: undefined symbol: jpeg_resync_to_restart
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFullPath(NativeLibLoader.java:201)

There is a function jpeg_resync_to_restart on my system:

$ objdump -T /usr/lib64/libjpeg.so.62 | grep resync
0000000000020950 g    DF .text	0000000000000126  LIBJPEG_6.2 jpeg_resync_to_restart

Is there a configuration error on my side?

**Comment by norbusan** [comment]
How did you install Java? It seems that the files shipped in your Java for JavaFX are not compiled against the JPEG library of your system.

I guess you need to contact Fedora about that, and retry with the Fedora provided Java.
